version: '3.9'

services:
  db:
    container_name: postgres-getjobfast
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=${TYPEORM_USERNAME}
      - POSTGRES_PASSWORD=${TYPEORM_PASSWORD}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    networks: 
      - back
 
  backend:
    container_name: backend-getjobfast
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    restart: unless-stopped    
    networks:
      - back
      - front    
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    environment:
      - TYPEORM_USERNAME=${TYPEORM_USERNAME}
      - TYPEORM_PASSWORD=${TYPEORM_PASSWORD}
      - TYPEORM_PORT=${TYPEORM_PORT}
      - TYPEORM_HOST=db
    env_file: .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db

  nginx:
    container_name: frontend
    build:
      context: ./
      dockerfile: ./frontend/Dockerfile
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
    restart: unless-stopped
    env_file: .env
    networks: 
      - front

networks:
  back:
    driver: bridge
  front:
    driver: bridge