version: '3.9'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    env_file:
      - .env
    restart: always
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    volumes:
      - mongodb_data_container:/data/db
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_DATEBASE}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    networks:
      - back
 
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    restart: unless-stopped    
    networks:
      - back    
    ports:
      - 4000:4000
    env_file: .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongodb

  nginx:
    container_name: frontend
    build:
      context: ./
      dockerfile: ./frontend/Dockerfile
    ports:
      - 80:80
    restart: unless-stopped
    env_file: .env
    networks: 
      - front

networks:
  back:
    driver: bridge
  front:
    driver: bridge

volumes:
  mongodb_data_container: