version: '3.9'

services:
  nginx:
    container_name: frontend
    build:
      context: ./
      dockerfile: ./frontend/Dockerfile
    ports:
      - 80:80
    restart: unless-stopped
    networks: 
      - front
 
  backend:
    build:
      dockerfile: ./Dockerfile
    networks: 
      - front

networks:
  front:
    driver: bridge