export const GET_USER_REQUEST: "GET_USER_REQUEST" = "GET_USER_REQUEST";
export const GET_USER_SUCCESS: "GET_USER_SUCCESS" = "GET_USER_SUCCESS";
export const GET_USER_FAILED: "GET_USER_FAILED" = "GET_USER_FAILED";
export const SET_NO_USER: "SET_NO_USER" = "SET_NO_USER";

export const GET_RESUMES_REQUEST: "GET_RESUMES_REQUEST" = "GET_RESUMES_REQUEST";
export const GET_RESUMES_SUCCESS: "GET_RESUMES_SUCCESS" = "GET_RESUMES_SUCCESS";
export const GET_RESUMES_FAILED: "GET_RESUMES_FAILED" = "GET_RESUMES_FAILED";

export const GET_SIMILAR_VACANCIES_REQUEST: "GET_SIMILAR_VACANCIES_REQUEST" = "GET_SIMILAR_VACANCIES_REQUEST";
export const GET_SIMILAR_VACANCIES_SUCCESS: "GET_SIMILAR_VACANCIES_SUCCESS" = "GET_SIMILAR_VACANCIES_SUCCESS";
export const GET_SIMILAR_VACANCIES_FAILED: "GET_SIMILAR_VACANCIES_FAILED" = "GET_SIMILAR_VACANCIES_FAILED";

export const SEND_MSG_REQUEST: "SEND_MSG_REQUEST" = "SEND_MSG_REQUEST";
export const SEND_MSG_SUCCESS: "SEND_MSG_SUCCESS" = "SEND_MSG_SUCCESS";
export const SEND_MSG_FAILED: "SEND_MSG_FAILED" = "SEND_MSG_FAILED";